### ISSUE TITLE
Non-fatal crash on player login

### ISSUE THREAD

**Issue by JavaProphet** [djxy/PermissionManager#2]
`java.util.NoSuchElementException: No value present ✓
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_45-internal]
        at io.github.djxy.permissionManager.PermissionManager$1.getCurrentWorld(PermissionManager.java:129) ~[PermissionManager$1.class:?]
        at io.github.djxy.permissionManager.pmSubjects.PMPlayerSubject.getPermissionValue(PMPlayerSubject.java:123) ~[PMPlayerSubject.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.getPermissionValue(EntityPlayerMP.java:147) ~[lf.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:129) ~[lf.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:141) ~[lf.class:?]
        at me.ryanhamshire.griefprevention.event.PlayerEventHandler.onPlayerLogin(PlayerEventHandler.java:666) ~[PlayerEventHandler.class:?]
        at org.spongepowered.common.event.listener.LoginListener_PlayerEventHandler_onPlayerLogin83.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1471]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:210) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1471]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:251) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1471]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:223) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1471]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.2.0-BETA-1471]
        at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:223) [lx.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:239) [NetworkDispatcher.class:?
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:190) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289) [ek.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189) [ll.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]`

Is shown whenever a player joins on my server.

**Comment by djxy** [comment]
You are using API 4.2.0, I haven't tested it, so it may have some bugs.
