### ISSUE TITLE
NPE: during server launch and when trying to autocomplete a command

### ISSUE THREAD

**Issue by Illyohs** [djxy/PermissionManager#4]
The PM throws a NPE during start up
```
06:58:27] [Server thread/ERROR] [Sponge/sponge]: Could not pass FMLPreInitializationEvent to org.spongepowered.mod.plugin.SpongeModPluginContainer@2648c4d6
java.lang.NoClassDefFoundError: io/github/djxy/permissionManager/pmSubjects/PMPlayerSubject
	at io.github.djxy.permissionManager.PMService.<init>(PMService.java:33) ~[PMService.class:?]
	at io.github.djxy.permissionManager.PMService.<clinit>(PMService.java:18) ~[PMService.class:?]
	at io.github.djxy.permissionManager.Main.onGamePreInitializationEvent(Main.java:158) ~[Main.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_Main_onGamePreInitializationEvent7.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2002-5.0.0-BETA-1550]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:210) [SpongeModEventManager.class:1.10.2-2002-5.0.0-BETA-1550]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:251) [SpongeModEventManager.class:1.10.2-2002-5.0.0-BETA-1550]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:205) [SpongeMod.class:1.10.2-2002-5.0.0-BETA-1550]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:593) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.ClassNotFoundException: io.github.djxy.permissionManager.pmSubjects.PMPlayerSubject
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_92]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_92]
	... 36 more
Caused by: java.lang.NoClassDefFoundError: org/spongepowered/api/service/permission/option/OptionSubject
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_92]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_92]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_92]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_92]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_92]
	... 36 more
Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.service.permission.option.OptionSubject
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_92]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_92]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_92]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_92]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_92]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_92]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_92]
	... 36 more
```
[Full log](http://sprunge.us/STbb)

There is also an error when trying to auto complete a command
 [error log](http://sprunge.us/BZAQ)

**Comment by Illyohs** [comment]
Looks like the first error came from this commit https://github.com/SpongePowered/SpongeAPI/commit/e3f88319f95698d4b5df9e4a7111a67b5b4b31a1 in sponge bleeding

**Comment by djxy** [comment]
I will check it today.

**Comment by rojo8399** [comment]
Still getting this error when registering an Enjin key.

**Comment by djxy** [comment]
Enjin doesn't work with PermissionManager v2.X, we will have to wait an update from their plugin.

**Comment by djxy** [comment]
I thought it's was PermissionManager v2, my bad. I'm not supporting PermissionManager v1.X, I let this version avalaible but I won't fix any bug.

**Comment by alicheek** [comment]
@djxy  This is still an issue on version permissionManager-2.2-API-5.X.jar and enjin just tested it out there will be great if you can help out :)

**Comment by alicheek** [comment]
also ive sent a message to the enjin team about it :)

**Comment by djxy** [comment]
I asked them like a month ago. I tried to fix it, but I can't do anything. Someone else asked them too.
