### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by 5igm** [djxy/PermissionManager#5]
DjxyCore-1.0.2.jar
PermissionManager-1.2.jar
spongeforge-1.10.2-2044-5.0.0-BETA-1649
forge-1.10.2-12.18.1.2044-universal
[20:13:27] [Server thread/INFO] [nucleus/]: Server ran the command: /pm 
[20:13:27] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'pm' for source DedicatedServer: null
java.lang.NullPointerException
	at io.github.djxy.core.translation.Translator.getTranslation(Translator.java:51) ~[Translator.class:?]
	at io.github.djxy.core.translation.Translator.translate(Translator.java:67) ~[Translator.class:?]
	at io.github.djxy.core.translation.Translator.translate(Translator.java:106) ~[Translator.class:?]
	at io.github.djxy.core.commands.nodes.Node.executeCommand(Node.java:46) ~[Node.class:?]
	at io.github.djxy.core.commands.Command.process(Command.java:27) ~[Command.class:?]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2044-5.0.0-BETA-1649]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:274) [SpongeCommandManager.class:1.10.2-2044-5.0.0-BETA-1649]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:82) [bd.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by djxy** [comment]
You are using Sponge API 5.0. I' currently working on a new version of the plugin for the Sponge API 5.0.

**Comment by 5igm** [comment]
Thanks for your help.

**Comment by djxy** [comment]
I'm currently working on the version to support the Sponge API 5.0
