### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by 5igm** [djxy/PermissionManager#7]
`[01:45:45] [Server thread/ERROR] [Sponge/]: Could not pass ServerChatEvent to org.spongepowered.mod.plugin.SpongeModPluginContainer@28a56b58
java.lang.NullPointerException
	at io.github.nucleuspowered.nucleus.modules.chat.config.ChatConfig.getTemplate(ChatConfig.java:37) ~[ChatConfig.class:0.6.0]
	at io.github.nucleuspowered.nucleus.modules.chat.listeners.ChatListener.onPlayerChat(ChatListener.java:110) ~[ChatListener.class:0.6.0]
	at org.spongepowered.common.event.listener.ChatListener_ChatListener_onPlayerChat89.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1653]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1653]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:148) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1653]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:92) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:81) [EventBus.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handler$injectChatEvent$0(NetHandlerPlayServer.java:78) [lm.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:799) [lm.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1653]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]`

In addition, I suggest to make some default file which has been setted. Now all of the config files are blank. It is really hard.

**Comment by djxy** [comment]
The error is from nucleus

**Comment by 5igm** [comment]
@djxy I still be confused of subject. Could you give an example if I want to use a command to grant all permision (*) to group owner?

**Comment by djxy** [comment]
A group owner?

**Comment by 5igm** [comment]
A group named owner. And I want to give all of permissions to this group.

**Comment by djxy** [comment]
If you modify the file, give it the permission '*'. If you give it with a command, the permission is *

**Comment by 5igm** [comment]
Yes, but I don't know what should I type in the position of subject. I'm using commands.

**Comment by djxy** [comment]
in the position of the subject?

**Comment by 5igm** [comment]
Could you give an example of a command? Like this one:

> /pm [player|group] [subject] set permission [permission] [value [value]]|[world [world] value [value]]

**Comment by 5igm** [comment]
I think after [player|group], I should type something for subject part, but I am confused what I should do. I have read the page, subject. I still cannot understand the definition of it. Could give me a command example to help me comprehend it?

> A subject is an entity that can have permissions and groups. A group and a player inherit of all the properties of the subject. That means you can set a subject property to a player and it will work.

**Comment by djxy** [comment]
/pm group owner set permission * value true

**Comment by djxy** [comment]
it should work.

**Comment by 5igm** [comment]
Thank you very much. I get it. Thanks.
