### ISSUE TITLE
Error occur when lauching server

### ISSUE THREAD

**Issue by 5igm** [djxy/PermissionManager#9]
spongeforge-1.9.4-1968-5.0.0-BETA-1503
PermissionManager-1.2
```
[18:32:36] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderException: java.lang.AbstractMethodError: io.github.djxy.permissionManager.PMService.getDefaults()Lorg/spongepowered/api/service/permission/Subject;

	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:831) ~[Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:290) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.AbstractMethodError: io.github.djxy.permissionManager.PMService.getDefaults()Lorg/spongepowered/api/service/permission/Subject;
	at net.minecraft.command.ServerCommandManager.registerDefaultPermissions(SourceFile:130) ~[bd.class:?]
	at net.minecraft.command.ServerCommandManager.registerCommandsList(SourceFile:141) ~[bd.class:?]
	at net.minecraft.command.ServerCommandManager.registerLowPriorityCommands(SourceFile:147) ~[bd.class:?]
	at org.spongepowered.mod.SpongeMod.onServerStarted(SpongeMod.java:275) ~[spongeforge-1.9.4-1968-5.0.0-BETA-1503.jar:1.9.4-1968-5.0.0-BETA-1503]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.4.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.4.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.4.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.4.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.4.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.4.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.4.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.4.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.4.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.4.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:830) ~[Loader.class:?]
	... 3 more
```

**Comment by djxy** [comment]
It's normal, the current version of PermissionManager doesn't support Sponge API 5.0. I will release the new version in the next two weeks.

**Comment by Fujikatoma** [comment]
a fix for this error would be fabolous

**Comment by djxy** [comment]
Yes, the new version of PermissionManager will work with Sponge API 5.0
